syntax = "proto3";

package notes;

option go_package = "./pkg/proto/note";

// Message для заметки
message Note {
  string id = 1;
  string title = 2;
  string content = 3;
  string user_id = 6;
  int64 created_at = 4;
  int64 updated_at = 5;
}

// Message для запроса создания заметки
message CreateNoteRequest {
  string title = 1;
  string content = 2;
  string user_id = 3;
}

// Message для запроса получения сущности по ID
message GetRequest {
  string id = 1;
}

// Message для запроса обновления заметки
message UpdateNoteRequest {
  string id = 1;
  string title = 2;
  string content = 3;
}

// Message для ответа с заметкой
message NoteResponse {
  Note note = 1;
}

// Message для ответа с несколькими заметками
message NotesListResponse {
  repeated Note notes = 1;
}

// Message для ответа об успешности операции
message SuccessResponse {
  bool success = 1;
  string message = 2;
}

// Пустое сообщение для запросов без параметров
message Empty {}

// Сервис для работы с заметками
service NotesService {
  rpc CreateNote(CreateNoteRequest) returns (NoteResponse);
  rpc GetNote(GetRequest) returns (NoteResponse);
  rpc UpdateNote(UpdateNoteRequest) returns (NoteResponse);
  rpc DeleteNote(GetRequest) returns (SuccessResponse);
  rpc ListNotes(Empty) returns (NotesListResponse);
}